### PR TITLE
(WIP) ReactApp for freespeech

### PR DESCRIPTION
**Pull request by Aurous**
React App written for free speech
Backend server with some endpoints

WIP

### CODE REVIEW

**Comment by fatfingers23** [comment]
Hey we really appreciate the PR! I pulled it and started looking at it some. I see it is still WIP.

I wanted to ask what you think React can bring to the table that we cannot do in Vue? I hate to see the effort spilt and have two web applications. especially with the Vue app already so far along and almost at a point we can release?

**Comment by Aurous** [comment]
React offers a component structure that will allow for building and reusing components made.

With the react project that I started working on it use routing that helps with security for the back-end I started making.

I think that React has a lot more complexity to it where as Vue is fairly simple and if anything having both might offer to more people to consider working on the project.

The biggest difference between the two projects is the back-end, I think that having that will help this project so that someone can host and anyone can access the site anywhere.

If anything I can start working on a better back-end to fuse with the current project?

**Comment by fatfingers23** [comment]
I think the backend may be a better contribution.

Vue also does all the things React does. Re usable components, routing, Vuex(based off of redux), and so on. So it offers the same things React does as a front end. And we already have it, along with plenty of people contributing. 

I looked at the api calls. It looks likes just using fetch which is a js native option. Works fine with Vue.

I really I appreciate it. Just don’t see why we should branch off on another direction when we already have the Vue project?  I see having two projects to maintain without any real benefit also adding a ton of over head to a community that is already doing this for free. 

I love the idea of a backend though! That was an item on down the road. Just now have it as a self contained. But with a backend we can share user keyboards between devices, have a store where people can download other people keyboards. The possibility are endless. 

Express.js looks like it has server less ability(not familiar with node as a backend)? Which would be great because we have been looking at some cheaper hosts that support server less and can always move to bigger hosts and node.js. Could add that. Looks like what you already have will translate and someone else with Vue knowledge could make the front end.

Again we really appreciate your pr. I pulled the project and took a look and it was looking good already so quick!

**Comment by aidankinzett** [comment]
Another option could be using something like firebase, and avoid a backend altogether

**Comment by fatfingers23** [comment]
I had thought about Firebase too. I also do not have experience with that either. My main concern with Firebase is the price if we hit limits. Where with express.js if we start hitting serverless limits by our host. I can see the merit in we can move to a vps, or container provider. Which may save us money vs Firebase. Also express can run on more hosts vs Firebase were locked into it. 

I would really love to hear any suggestions or experiences any one may have on this. I don’t think a backend is needed immediately, but would add a lot to the project.

**Comment by Aurous** [comment]
If you would like to shoot me an email I would love to see where you are at with the back-end and if I can contribute any to developing that further!

You can close this pull if you would like!

**Comment by fatfingers23** [comment]
I'll probably reach out tomorrow. Getting late here. I know we can find somewhere you can contribute to the project with your skill set. I'm thinking the backend might be a great place for it!  Thanks again.

**Pull request closed without merging**
