### PR TITLE
Simplify stylesheet link

### PR DESCRIPTION
**Pull request by MatthewSH**
To help simplify external network calls, we should probably pull all the CSS and font files to the same repo. 

Also, considering it's in production, we should specify the MDI reference instead of opening up risk of breaking changes by referencing `@latest` in the link.

## ToDo List

- [x] Move references to their own files
- [x] Change references to external font files to local (Roboto)
- [x]  Change references to external font files to local (MDI)

### CODE REVIEW

**Comment by fatfingers23** [comment]
I'm not sure if i fully agree with these changes.
- Google material icons is installed via npm package now. So i don't acutally thing the stylesheet link does anything for that. I may be wrong but i just removed the line from your branch. Built and material icons still show just fine. So that line actually needs to be removed anyhow from master if we didn't merge your changes. 

- As for moving away from cdn. What do you think the benefit of this will be? I'm thinking we would want the benefits of cdn. Especially off loading that load to other providers design for that. Saving our serve the traffic load? Or some of the other things cdn brings to the product.  Not that i disagree with it fully, just curious what the benefit would be for keeping them local?

**Comment by MatthewSH** [comment]
So for the material iconset, I think most references look toward a font family, I'll go through the injected code and see if it's actually injecting the font into it. Mainly left it as a fallback, I saw the same thing you did.

While CDNs are fantastic, on production builds it's usually a good idea to have them locally. Not necessarily for speed, but mainly for security, stability, and versioning. Originally the MDI reference was marked as `@latest` which, in theory, at some point down the line break something somewhere. On top of that, if this were to be built and published it could possibly have issues with approval because Apple specifically doesn't like external references. As well as caching, in some cases can be improved. 

On top of that, it gives us an opportunity to change those files to fit our needs, and simplify the file size/load size itself, reference to 3101c75d4ff98f75ab2d0c978cf7973f2e772394 as most other languages/extensions aren't needed besides the base latin font.

I know there can be the certificate/security warnings on some browsers for external scripts, although I've only seen this a couple times...still a concern and the files from 3rd party sources could be blocked on the network, or even country level (very unlikely for the type of files we're requesting).

On top of that, although the file on the CDN has probably been pre-cached considering the target audience there's no guarantee in the type or quality of the device rendering the page and serving it locally will give us another point of optimization where we can help that.

While CDNs do have a lot of good sides, and I definitely don't disagree with them...I think for the sake of this project, which is more proposed like an app, it may be safer to go ahead and move files locally to ensure the resource availability at all times.

**Comment by fatfingers23** [comment]
Got me sold on hosting them locally! Thank you for posting a great explanation. That really help clear it up and was really informative for me. 

I went through it all and really looked at it to get a good understanding on everything and I think we should leave material icons how they are. Remove the css link to google on the `public/index.html`. Reason why. Seems like we are already actually hosting the icons on our project lol. The package `material-design-icons-iconfont` is a community maintained version of material icons. It is what was in Vuetify documentation. In the Vuetify.js file it imports the css file to Vuetify and uses the css/fonts from the package that is installed. 

Keeping it this way gets the same effect you were going for. But as a npm package we can lock the version, then we ever decide to change we can just change the version and update. Also keeps our decencies to npm so we don't have to change one manually and one in npm. Keeps it organized. 

As for us being able to cut down the size. I dont think Material icons is a big enough of an offender to worry about that. Especially with how easy it is to manage with npm. Of course any of this is open to debate if you think I got anything wrong or still feel like this pr is a better way. I really appreciate the issues and time you have been putting into this. 
image

**Comment by samwightt** [comment]
Adding onto this, if you're using any Google Fonts files it's generally recommended to load those from the Google Fonts CDN just because it's highly likely that they're already in a user's browser cache. If you keep them installed locally it not only slows down build times (admittedly by a little bit), but you also lose the performance benefits of those caching.

**Comment by silentnoodlemaster** [comment]
the caching benefits from google fonts @samwightt mentioned really only apply to first time visitors, since the local fonts could be cashed to the client when they visit. after all this is the type of app you would use more than once. 

But then again, first impressions are important, so there is really no correct answer

**Comment by fatfingers23** [comment]
I think we are going leave as is. Currently it loads them from the npm library. So they are hosted on the same server as Freespeech is hosted along with the CDN on the public index.html for backup.

**Pull request closed without merging**
