### PR TITLE
Qol updates and Voice change

### PR DESCRIPTION
**Pull request by fatfingers23**
Saw your posts on TikTok and really liked the idea so i wanted to help out and contribute some!

Quality of Life changes
* Added Python String Interpolation on buildmain.py to help with readability and hopefully to cut down on html errors.
* Added an gitingore.
* Added an requirements.txt with dependencies.

Moved the voice processing away from Say to [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis). This is a web browser native api which allows you to get away from the desktop/mac needed for this program. This makes the program full accesible from the web now. So you could move the project to Django/flash to have a python web application. Or can move it all to a Javascript frame work, drop python and have it ready to be made into a mobile app and webapp.

Would love to help out more if you need it! Have some great ideas on how you could get this to production and multi platform.

### CODE REVIEW

**Comment by reesdraminski** [comment]
Coming from TikTok as well!

+1 for SpeechSynthesis because it seems like it has good support on all devices.

I think [Flask](https://flask.palletsprojects.com/en/1.1.x/) would be better than Django just because it's more lightweight and he probably won't need the super-advanced logic that Django supports for a fully-featured web application. 

I think @Merkie chose Python because it's the language that they're most comfortable with. I don't think going full JavaScript would be that necessary if the learning curve would be big.

@Merkie feel free to email me reesd1@umbc.edu I think this project is amazing and would love to be a resource if I could.

**Comment by Merkie** [comment]
Thanks guys! Yeah for sure I’ll email you if I need any assistance. I did choose Python because it is a Lang I’m familiar with, however I’m learning js and web development.

**Comment by fatfingers23** [comment]
I been thinking on this the past couple days and thought i would share some different routes you could take FreeSpeech down. I would like to help any way i can. I can prime any of these and get it started for you, then you can take it from there. Or can point you to some documentation and tutorials on any of these options if you would like. If you have any questions or want me to explain anything can reach me at <baileytownsend2323@gmail.com>.

### Client Based Web Application
Could keep this fully in the web and accessible by the browser. Could do it in plan HTML/Js like it is now minus any python. Or use a JS Framework like [Vue](https://vuejs.org/), [React](https://reactjs.org/), or [Angular](https://angular.io/). Can then store the user settings, text, pictures in [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). No need for a backend or user based system. The user will be able to access it from their Desktop, phone, or any device with a web browser. Then could build a system where the user changes their settings from the ui and it only changes it for them and no other user. This would probably be the fastest and easy way to get it going

### Client Web Application With Flask Backend
This would be the same front end design as above. Expect you use a user system and store the settings in a database and serve the application with the Python web framework Flask.  The user would have a login and be able to login from any web browser to access the application

### Native Script App
This would be the option to go with if you wanted to learn JS and have it on the App store and Google store.  [Native Script](https://www.nativescript.org/) lets you write cross platform mobile apps with a JS framework and a Html like templateing for the UI. Would use this [NPM package](https://www.npmjs.com/package/nativescript-texttospeech) for voice processing and works with both android and ios. Then would store settings with one of these [options](https://www.nativescript.org/blog/client-side-storage-in-nativescript-applications).

**Comment by Merkie** [comment]
Thanks for the info, I'm planning on keeping the main application of Freespeech online and static meaning that it wouldn't editable. There is substantial research showing that static AAC applications work better, because the user can memorize the buttons similar how we memorize where the keys are on a qwerty keyboard. I'll probably make an editor feature once I'm more comfortable with JS.

I am having an issue with SpeechSynthesis not working on mobile. I've tried on Chrome on iOS and android and safari on iOS. Are there any other alternatives to SpeechSynthesis for mobile? Or a way I can get SpeechSynthesis to work on mobile?

**Comment by fatfingers23** [comment]
Sounds good to me! Feel free to reach out if you have any questions or best ways to do that!

I just submitted pr #5. I believe this will solve your issue. I pulled latest and it was doing the same for me even on desktop. But it should be working now.

**Pull request merged**
