### PR TITLE
Add .editorconfig so that many IDEs will know to use 2 spaces for indent

### PR DESCRIPTION
**Pull request by edlinklater**
Many IDEs will read this file, should help reduce issues like @samwightt is having in #53

### CODE REVIEW

**Comment by fatfingers23** [comment]
Does this effect eslinter? Also does this only trigger on "Format on save" inside of vscode?

**Comment by edlinklater** [comment]
Doesn't effect eslinter at all. This is to hint to browsers _at time of file open_ how they should work with files, rather than being something that runs and fixes afterwards.

I think it requires a plugin to work in VSCode, but it works automatically. in JetBrains IDEs and "full" Visual Studio.

see https://editorconfig.org/

**Comment by fatfingers23** [comment]
Sweet! I'll look at it later and make sure there is no fighting between them with current setups and probably merge this.

**Comment by fatfingers23** [comment]
Looks great to me! Thank you for your help on this and setting it up. 

Does the .editorconfig need to change any so eslint and it wont fight if someone is using that config during development?

**Comment by edlinklater** [comment]
@fatfingers23 No, its rules now match the eslint ones. Eslint will always "win" as editorconfig is considered a _hint_ to the IDE whereas eslint is considered _rules_ :)

**Pull request merged**
