### PR TITLE
Import/export settings and custom tile pad

### LINKED ISSUE #59: Export/Import Custom Keyboard
**Is your feature request related to a problem? Please describe.**
This will allow you to save your keyboard or manually share for now. Or even back it up in the case of a software failure.

**Describe the solution you'd like**
As a User, 
I would like to be able to export/import keyboard layouts via settings,
so that i have more control over the keyboard across devices, or can back it up. 

I would like to see it export the .json file and can be "uploaded" if possible. I don't think a text field will be a good ui design for exporting and importing. Not sure if that functionality can be achieved with no back end.

So it would look like you are uploading a json file for import, or downloading it for export.

### PR DESCRIPTION
**Pull request by edlinklater**
Fixes #59

### CODE REVIEW

**Comment by MatthewSH** [comment]
I don't know how I feel about this, simply thinking about the end user here. There's no guarantee that people will be technologically advanced enough for this and considering the keyboard for the most part will be used on mobile devices....transferring the files back and forth can be tricky for the common user. 

I'd, personally, rather go through a back end and make the overall experience better for the user first rather than implement these more engineer/developer type options. 

All of us are developers, so we think "oh this is super straight forward and clear." I'm just thinking like my sister or some other people in my family who aren't as technologically inclined and they would definitely have trouble understanding how to do this. Maybe we should backlog #59 until a decision has been made on #50

**Comment by edlinklater** [comment]
@MatthewSH Just developing what was requested in #59. I agree that file-based isn't the optimal setup, but I think it is better than nothing in the meantime.

What we could do is hide it (and probably also the reset button) behind an "advanced" area of the settings, so that it is less likely to confuse the average user.

**Comment by MatthewSH** [comment]
I think instead of just developing to the issues, which can lead to a very messy app, we should go back to the issue and discuss possible implementations or changes to the idea itself. It feels like there's almost a rush to close issues but not a clear, concise plan of action for some of the more crucial points which could have a severe effect on these PRs in the future or could lead to very messy, non-standardized codebase that looks like 10 people wrote it. Obviously it's up to @fatfingers23 and @Merkie at the end of the day, but that's just my thoughts on that.

**Comment by fatfingers23** [comment]
I agree with you @MatthewSH. I think this would be better handled by backend. But with the initial launch and us doing it as cheaply as we can with the model that it is all client based. 

Now why would we want a reset settings and export/import feature? My main thought is support. What are we going do if we release a bug that renders the app useless because of a faulty read/write to the localstorage? I can't guarantee that would never happen because it has happen to me twice now, and i believe you even submitted a pr that needed the localstorage to be reset. What would we tell a user who is using the app on the Ipad? Switch browsers? Or what if a user spent all of this time creating a keyboard, like all day and then they had to reset their keyboard. I would be upset and consider moving to one of our competitor applications. I envision us making a FAQ and support documentation before launch and even recommend to users to back up their settings. I know it will not solve every issue, but it sure will help. Be great for bugs as well "Please post your settings". 

We are trying to deliver an application that will rival the paid ones, giving people access to those amazing features for free to help give a voice to those who have trouble vocalizing. I want to make sure we can make something people can truly depend on, trust, and use daily. 

These may not be some of the best solutions, but they are better than none and took minimal time to implementation and the best i can see centered around an all client based application. I agree to we do need a more clear view. I started working on that a little today during lunch with the milestones. I will work with @Merkie  to create a roadmap to help with the over all vision.

I appreciate your concerns about this. I want the same things I'm sure you do. A successful app that really makes a difference and helps people.

**Comment by fatfingers23** [comment]
I believe this pr resolves the issue and is a great addition. I am going go a head and pull it in. If we decide to move these settings to a new location we can decide that in another issue.

**Pull request merged**
