### PR TITLE
Spacing format, and other formatting by eslint

### PR DESCRIPTION
**Pull request by fatfingers23**
I added spacing formatting along with a few others via Eslint. I think Eslint is going be the way to go for this project. With eslint i can set up some GitHub actions to lint and notify the author of the PR that their is linting  differences so it saves me time and keeps the code formatted correctly. 

If i don't hear any major complaints by about mid day or a bit later i'll merge.

### CODE REVIEW

**Comment by edlinklater** [comment]
Just confirming what the indentation rules are meant to be? This seems to be changing from spaces everywhere to tabs inside of <script> tags and spaces everywhere else, which I think is a bit confusing. Wouldn't it be better to use either tabs or spaces universally?

**Comment by fatfingers23** [comment]
That is confusing! I'm going be honest. Elinter is a wonderful tool that i have yet to fully wrap my head around. It's usually a week battle of me setting it up the way i want on a new project. Do you have suggestions on how i can get it to lint everything as tab spacing?

**Comment by MatthewSH** [comment]
I believe the rule `no-mixed-spaces-and-tabs` should do it, it's been a while since I've configured it to be honest.

**Comment by edlinklater** [comment]
@fatfingers23 Needs the `vue/html-indent` rule set up :) I've applied this now in #55

**Pull request merged**
