### PR TITLE
Allow for headless server testing

### PR DESCRIPTION
**Pull request by Aurous**
I do my tests from a VPS and adding these settings will make it possible for others to test from non-localhost computers.

https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck
https://webpack.js.org/configuration/dev-server/#devserverport
https://webpack.js.org/configuration/dev-server/#devserverhost

### CODE REVIEW

**Comment by MatthewSH** [comment]
Uhh, not sure why all the React PR is in there, so not sure if it's a good idea to have that. Did you base your branch off that PR?

**Comment by Aurous** [comment]
I'm not sure how to only pass the commit that is necessary, I made a PR last night with a react app core that I have removed from my branch. As you can see from the files changed it is only the vue.config.js file that I have added some lines into that will affect the way that the test server is being started.

**Comment by fatfingers23** [comment]
I think the git method you are looking for is called Squash. I usually use the GUI tool [GitKraken](https://support.gitkraken.com/working-with-commits/squash/) for this. Great Git GUI tool as well. Let me know if you have any questions on how to use it. I don't mind helping out.

**Comment by Aurous** [comment]
I will resubmit after I get gitkraken working, I apologize, I'm used to solo work.

**Comment by MatthewSH** [comment]
In the future, probably a good idea to never work off of your master branch. If you use branches, will be easier to create new features and fixes without having issues like these.

**Comment by fatfingers23** [comment]
Don't apologize at all! We've all been there Git is a beast of a thing to learn. This is the the nice part of Open source. Gives you a chance to learn the software development cycle. Please reach out to me if you need any help or questions.

**Comment by MatthewSH** [comment]
Also @fatfingers23 was kind enough to write a simple guide for it: https://github.com/Merkie/freespeech/blob/master/.github/CONTRIBUTING.md#-pull-request-process

Honestly really good for people new to open source contributions.

**Comment by fatfingers23** [comment]
Thank you @MatthewSH. I can't take all of the credit for that as much as i would like to haha. I did change some of it, but most of the commands and text was taken from the people over at [Runelite](https://github.com/runelite/runelite/blob/master/.github/CONTRIBUTING.md). They wrote such an easy to understand explanation of the process that cookie cutter fits anywhere i used it for our project 😄.

**Pull request closed without merging**
