### PR TITLE
Add more visual distinction when in edit mode.

### PR DESCRIPTION
**Pull request by MatthewSH**
Edit mode is still a bit hard to see, even with the visual navbar color change. So to help counter that in this PR I've added a small animation library, [WickedCSS](http://kristofferandreasen.github.io/wickedCSS/), and added a simple pulse animation. This will also give us the ability to add visual feedback on button taps in the future as well, and only adds a few ms to load time.

So when a user goes into edit mode, a card stating that the user is in edit mode as well as a save button appears and the pulse animation is added to the cards so that the user can see the cards are in edit mode as well.

### CODE REVIEW

**Comment by aidankinzett** [comment]
Screen Shot 2020-02-20 at 10 19 04 pm
The pulsing of the tiles is cool, but its not necessary to have two separate cards saying that your in edit mode. The one that was already there fit the styling with the sentence card better

**Comment by MatthewSH** [comment]
Uhhh, @aidankinzett that's weird. It doesn't have more than one. Clear your local storage. This is what it looks like for me: https://i.imgur.com/cJjalEy.gifv

**Comment by aidankinzett** [comment]
Yeah clearing local storage, even icognito didnt change it. The other code is currently in master, it was added when pull request #49 was merged

**Comment by MatthewSH** [comment]
Well, it turns out the issue was closed and resolved without it ever being assigned or referenced in the PR so I had no idea anyone was even working on it. If, in the future, people could open a draft PR to a WIP branch or have someone assign an issue to them so that people who aren't consistently on monitoring that specific issue know that it's in the works or currently being worked on...that would be appreciated.

**Comment by fatfingers23** [comment]
Hey @MatthewSH  that was my mistake. I did not link the pr to the issue correctly. But i did close it last night and added the comment. 

> Pr #49 solved these.

I would imagine that would notify you sense you were the creator of the issue.
I'll go a head and link it for record keeping and will try to link prs to issues better in the future. Thank you for your work!

**Comment by MatthewSH** [comment]
@fatfingers23 it's not on you. It's that the general idea of PRs is that you only open them when they're completed when that's not the case. IF someone were to open a PR right after they push a branch to their origin then they can mark it as draft so it still exists, just can't be merged. Then by putting even the issue number in the title will show in the original issue that there is a PR in existence for it. I check PRs more commonly than issues, so if I were to see yesterday that someone was already working on it, I wouldn't have created the branch locally before I fell asleep. It's more of a mindset thing than anything. It shouldn't be up to the project collaborator to match PRs to Issues but the contributor to make sure the PR is referencing the issues that they're working on.

**Comment by MatthewSH** [comment]
In the contributing guidelines, maybe we can PR a section that explains the contribution process to avoid future issues such as this?

Like:
> When you're wanting to contribute, please request that a currently open issue be assigned directly to you. 
> Once you're assigned the issue, then you can create a branch and push it to your origin so that you can create a draft PR that can't be merged to master but still exists as a work in progress PR so the community can both follow changes, and make recommendations. 
> In the PR title, reference the issue number that you're currently working on so GitHub can link it from the original issue.
> Upon completion of the issue, mark the PR as ready for review so it can be officially reviewed and merged/closed.

**Pull request closed without merging**
