### PR TITLE
chore(license): add license

### LINKED ISSUE #36: choose a license
please choose a license for this project :)

### PR DESCRIPTION
**Pull request by cyberhck**
since this is under MIT license, having a license.md will show license on gh UI, 
closes #36

### CODE REVIEW

**Comment by fatfingers23** [comment]
Could you move this to the docs folder like the Contributing.md? Trying keep them all together and just have the ReadMe on the main folder. Thank you!

**Comment by fatfingers23** [comment]
Honestly I looked at this again. It probably is best to have the under .github. Frees doc folder for if we add documentation. Thank you!

**Comment by cyberhck** [comment]
github's convention for license is to have it on root, that way MIT shows up in your repo:
image

**Comment by cyberhck** [comment]
I can sent another PR moving into another directory, but I don't think you want that,

**Comment by fatfingers23** [comment]
Nah no worries. I think it’s good there. I read where it could live at .github or docs folder. But I didn’t want to make the commits to test and see if it would still show up on UI on the home page lol. Thanks for the contribution!

**Pull request merged**
